const Detail = [
    {
        id: 1,
        Title: "product 1",
        Price: 2500,
        Img:"./img/shoes1.png",
        Cate: "shoes",
    },
    {
        id: 2,
        Title: "product 2",
        Price: 3000,
        Img:"./img/shoes2.webp",
        Cate: "shoes",
    },
    {
        id: 3,
        Title: "product 3",
        Price: 3500,
        Img:"./img/shoes3.png",
        Cate: "shoes",
    },
    {
        id: 4,
        Title: "product 4",
        Price: 2500,
        Img:"./img/shoes4.webp",
        Cate: "shoes",
    },
    {
        id: 5,
        Title: "Puma SpeedCat OG",
        Price: 4000,
        Img:"./img/shoes5.avif",
        Cate: "shoes",
    },
    {
        id: 6,
        Title: "Puma ProFoam",
        Price: 3100,
        Img:"./img/shoes6.avif",
        Cate: "shoes",
    },
    {
        id: 7,
        Title: "Puma Cali Court",
        Price: 2000,
        Img:"./img/shoes7.avif",
        Cate: "shoes",
    },
    {
        id: 8,
        Title: "Puma Suede",
        Price: 2200,
        Img:"./img/shoes8.avif",
        Cate: "shoes",
    },
    {
        id: 9,
        Title: "Anta KT 3",
        Price: 2200,
        Img:"./img/shoes9.webp",
        Cate: "shoes",
    },
    {
        id: 10,
        Title: "Anta Whirlwind",
        Price: 2200,
        Img:"./img/shoes10.webp",
        Cate: "shoes",
    },
    {
        id: 11,
        Title: "Anta KT 9",
        Price: 2200,
        Img:"./img/shoes11.webp",
        Cate: "shoes",
    },
    {
        id: 12,
        Title: "Anta Men Z-UP",
        Price: 2200,
        Img:"./img/shoes12.webp",
        Cate: "shoes",
    },
]

export default Detail;